import streamlit as st
import pandas as pd
import google.generativeai as genai
import plotly.express as px
from io import StringIO
from sap_ypp_career_navigator.data_utils import load_certificates
from sap_ypp_career_navigator.nlp import extract_keywords
from sap_ypp_career_navigator.recommender import recommend_certificates
from sap_ypp_career_navigator.gemini_agent import get_gemini_recommendation

# Custom CSS for modern dark theme
st.markdown("""
    <style>
        .stApp {
            background-color: #1e1e1e;
            color: white;
        }
        .stButton>button {
            background-color: #4CAF50;
            color: white;
        }
        .stTextInput>div>div>input {
            background-color: #333;
            color: white;
        }
        h1, h2, h3 {
            color: #4CAF50;
        }
    </style>
    """, unsafe_allow_html=True)

# Load SAP certificates
certificates_df = load_certificates()
cert_names = certificates_df.iloc[:, 0].dropna().unique().tolist()

# Predefined competencies
technical_skills = [
    'Python', 'SQL', 'Data Analysis', 'S/4HANA', 'FICO', 'MM', 'SD', 'ABAP', 'Cloud', 'Analytics', 'Power BI', 'AI/ML', 'Integration'
]
non_technical_skills = [
    'Communication', 'Project Management', 'Leadership', 'Client Management', 'Presentation', 'Teamwork', 'Problem Solving', 'Adaptability'
]

st.title('SAP YPP Career Navigator')
st.subheader('Own Your Journey: Data-Driven Career Strategy for YPP Graduates')
st.write('Enter your profile to get a personalized, data-driven SAP career roadmap.')

with st.form('profile_form'):
    st.subheader('Your SAP Profile')
    user_certs = st.multiselect('Current SAP Certificates', cert_names)
    user_tech = st.multiselect('Technical Competencies', technical_skills)
    user_tech_free = st.text_input('Other Technical Skills (comma-separated)', '')
    user_nontech = st.multiselect('Non-Technical Competencies', non_technical_skills)
    user_nontech_free = st.text_input('Other Non-Technical Skills (comma-separated)', '')
    user_interests = st.text_area('Your Interests (e.g., AI in Finance, Supply Chain Optimization)')
    user_dream = st.text_area('Dream Career Position (e.g., SAP Solution Architect)')
    user_exp = st.slider('Years of Experience', 0, 10, 0)
    submitted = st.form_submit_button('Analyze My Profile')

if submitted:
    tech_all = user_tech + [s.strip() for s in user_tech_free.split(',') if s.strip()]
    nontech_all = user_nontech + [s.strip() for s in user_nontech_free.split(',') if s.strip()]
    profile = {
        'certificates': user_certs,
        'technical_skills': tech_all,
        'non_technical_skills': nontech_all,
        'interests': user_interests,
        'dream_position': user_dream,
        'years_experience': user_exp
    }
    keywords = extract_keywords(user_interests + ' ' + user_dream)
    st.write('### Your Profile')
    st.json(profile)
    st.write('### Extracted Keywords')
    st.write(keywords)

    # Recommend up to 4 certificates
    recommended = recommend_certificates(keywords + tech_all + nontech_all, certificates_df)
    recommended = recommended[:4]
    st.write('### Top 4 Certificate Recommendations')
    for cert in recommended:
        st.success(cert.get(certificates_df.columns[0], str(cert)))

    # Market demand summary (static for now, can be improved)
    market_summary = (
        "In Kenya, S/4HANA, FICO, and MM are the most in-demand SAP modules. "
        "Cloud and AI/ML skills are increasingly valuable globally. "
        "Employers seek hybrid profiles: strong SAP expertise plus business/tech skills."
    )

    # Gemini API key (for now, hardcoded as per your instruction)
    api_key = "AIzaSyAGWwNO7EuOHVx5YraWEPaPSgfCMD-qvD8"

    # Build prompt and call Gemini
    with st.spinner('Generating your personalized career roadmap...'):
        ai_response = get_gemini_recommendation(
            user_profile=profile,
            extracted_keywords=keywords,
            certificates_df=certificates_df,
            api_key=api_key
        )
    st.markdown('---')
    st.header('🎯 Your Personalized SAP Career Dashboard')
    st.markdown(ai_response)
    st.info('This dashboard is generated by an AI agent using your profile, market data, and SAP certification options.') 